version: '3'
services:
  mysql:
    image: mysql:5.7
    environment:
      - TZ=Asia/Tokyo
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=sakanatsuritai_dev_user
      - MYSQL_PASSWORD=sakanatsuritai_develop
      - MYSQL_DATABASE=sakanatsuritai_develop
    ports:
      - '3306:3306'
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d/:ro
      - mysqldata:/var/lib/mysql
    networks:
      - default
  app:
    build:
      context: ./docker      # Dockerfile保存場所
      dockerfile: Dockerfile    # Dockerfileファイル名
    env_file: ./app.env
    environment:
      - TZ=Asia/Tokyo
      - DEBUG=app:*
    image: node_app_sakanatsuritai               # イメージ名
    container_name: node_app_sakanatsuritai       # コンテナ名
    ports:                          # ポート接続
      - 3000:3000
    volumes:                        # mount workdir
      - ./myapp:/src
    command: [sh, -c, npm install && npm run watch]
    networks:
      - default
    depends_on:
      - mysql
networks:
  default:
# コンテナが削除されてもデータが消えずに保持される
volumes:
  mysqldata: